//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace posting.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YMGW-PC\\MSSQLSERVER2")]
        public string sServer {
            get {
                return ((string)(this["sServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("darwin")]
        public string sDataBase {
            get {
                return ((string)(this["sDataBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string sUI {
            get {
                return ((string)(this["sUI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sqlpass")]
        public string sPs {
            get {
                return ((string)(this["sPs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YMGW-PC\\MSSQLSERVER2;Initial Catalog=darwin;Persist Security Info=Tru" +
            "e;User ID=sa;Password=sqlpass")]
        public string darwinConnectionString {
            get {
                return ((string)(this["darwinConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("発注書.xls")]
        public string エクセル発注書シート名 {
            get {
                return ((string)(this["エクセル発注書シート名"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入庫管理表.xls")]
        public string エクセル入庫管理表シート名 {
            get {
                return ((string)(this["エクセル入庫管理表シート名"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("営業担当者別受注一覧ヨコ.xls")]
        public string エクセル営業担当者別受注一覧シート名 {
            get {
                return ((string)(this["エクセル営業担当者別受注一覧シート名"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("配布指示報告書.xls")]
        public string エクセル配布指示報告書 {
            get {
                return ((string)(this["エクセル配布指示報告書"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("配布完了報告書.xls")]
        public string エクセル配布完了報告書 {
            get {
                return ((string)(this["エクセル配布完了報告書"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("配布進捗状況.xls")]
        public string エクセル配布進捗状況 {
            get {
                return ((string)(this["エクセル配布進捗状況"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("配布員稼動数一覧.xls")]
        public string エクセル配布員稼動数一覧 {
            get {
                return ((string)(this["エクセル配布員稼動数一覧"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("配布料請求書受領証.xls")]
        public string エクセル配布料請求書受領証 {
            get {
                return ((string)(this["エクセル配布料請求書受領証"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("配布料請求書.xls")]
        public string エクセル配布料請求書 {
            get {
                return ((string)(this["エクセル配布料請求書"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("請求書2015.xls")]
        public string エクセル請求書 {
            get {
                return ((string)(this["エクセル請求書"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("クライアント別請求一覧ヨコ.xls")]
        public string エクセルクライアント別請求一覧 {
            get {
                return ((string)(this["エクセルクライアント別請求一覧"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int 販促手当率 {
            get {
                return ((int)(this["販促手当率"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("販売促進手当.xls")]
        public string エクセル販売促進手当 {
            get {
                return ((string)(this["エクセル販売促進手当"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("配布スケジュール.xls")]
        public string エクセル配布スケジュール {
            get {
                return ((string)(this["エクセル配布スケジュール"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("対比表.xls")]
        public string エクセル対比表 {
            get {
                return ((string)(this["エクセル対比表"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("累計表.xls")]
        public string エクセル累計表 {
            get {
                return ((string)(this["エクセル累計表"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("チラシ在庫管理表.xls")]
        public string エクセル在庫管理表 {
            get {
                return ((string)(this["エクセル在庫管理表"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メニュータイトル.csv")]
        public string menuCsv {
            get {
                return ((string)(this["menuCsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("振り表.xls")]
        public string エクセル振り表 {
            get {
                return ((string)(this["エクセル振り表"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("受注確定書.xlsx")]
        public string エクセル受注確定書 {
            get {
                return ((string)(this["エクセル受注確定書"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("受注確定書印刷.xlsx")]
        public string エクセル受注確定書印刷 {
            get {
                return ((string)(this["エクセル受注確定書印刷"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("営業売上表.xls")]
        public string 営業売上表 {
            get {
                return ((string)(this["営業売上表"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("納品書.xls")]
        public string エクセル納品書 {
            get {
                return ((string)(this["エクセル納品書"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("クライアント別受注一覧.xlsx")]
        public string エクセルクライアント別受注一覧 {
            get {
                return ((string)(this["エクセルクライアント別受注一覧"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("クライアント別受注別集計.xlsx")]
        public string エクセルクライアント別受注別集計 {
            get {
                return ((string)(this["エクセルクライアント別受注別集計"]));
            }
        }
    }
}
